import type { Question } from './types';

/**
 * Question bank for ReadQuest, authored across Grades 1-3 and all six literacy
 * strands. Each strand carries roughly ten items per grade so the adaptive
 * engine always has somewhere to slide as a learner's rating moves.
 *
 * Conventions:
 *  - `grade` (1-3) tags the target school grade.
 *  - `difficulty` is the Elo rating that actually drives selection. Items sit
 *    inside their grade's band (see GRADE_BANDS in types.ts):
 *      Grade 1 ≈ 700-950, Grade 2 ≈ 960-1200, Grade 3 ≈ 1220-1480.
 *  - ids follow `{strand}-g{grade}-{kc}-{n}` and must be unique.
 *
 * Later phases swap this static list for a database-backed, generated bank;
 * the shapes here are the contract that lets that happen without UI changes.
 */
export const QUESTION_BANK: Question[] = [
  // ===================================================================
  // PHONICS — Phono Shores (letter sounds, decoding)
  // ===================================================================
  // ---- Grade 1: CVC, initial/final sounds, short vowels, first digraphs ----
  { id: 'ph-g1-cvc-1', strand: 'phonics', grade: 1, kc: 'cvc', difficulty: 700,
    type: 'spelling', prompt: 'Spell the word for a pet that says "woof".',
    answer: 'dog', hint: 'd-o-g.' },
  { id: 'ph-g1-shortvowel-1', strand: 'phonics', grade: 1, kc: 'short-vowels', difficulty: 720,
    type: 'multiple-choice', prompt: 'Which word has the short "a" sound, like in "apple"?',
    choices: ['cat', 'cake', 'corn', 'cube'], answerIndex: 0 },
  { id: 'ph-g1-cvc-2', strand: 'phonics', grade: 1, kc: 'cvc', difficulty: 740,
    type: 'spelling', prompt: 'Spell the word that names the star we see in the day sky.',
    answer: 'sun', hint: 'It starts with /s/: s-u-n.' },
  { id: 'ph-g1-initial-1', strand: 'phonics', grade: 1, kc: 'initial-sounds', difficulty: 760,
    type: 'multiple-choice', prompt: 'Which word starts with the /b/ sound?',
    choices: ['bat', 'hat', 'mat', 'rat'], answerIndex: 0 },
  { id: 'ph-g1-cvc-3', strand: 'phonics', grade: 1, kc: 'cvc', difficulty: 780,
    type: 'spelling', prompt: 'Spell the word for a farm animal that says "oink".',
    answer: 'pig', hint: 'p-i-g.' },
  { id: 'ph-g1-rhyme-1', strand: 'phonics', grade: 1, kc: 'rhyming', difficulty: 800,
    type: 'multiple-choice', prompt: 'Which word rhymes with "hat"?',
    choices: ['cat', 'dog', 'cup', 'sun'], answerIndex: 0 },
  { id: 'ph-g1-cvc-4', strand: 'phonics', grade: 1, kc: 'cvc', difficulty: 820,
    type: 'spelling', prompt: 'Spell the word for the thing you sleep in at night.',
    answer: 'bed', hint: 'b-e-d.' },
  { id: 'ph-g1-digraph-1', strand: 'phonics', grade: 1, kc: 'digraphs', difficulty: 840,
    type: 'multiple-choice', prompt: 'Which word has the "sh" sound?',
    choices: ['fish', 'fin', 'top', 'run'], answerIndex: 0 },
  { id: 'ph-g1-cvc-5', strand: 'phonics', grade: 1, kc: 'cvc', difficulty: 860,
    type: 'spelling', prompt: 'Spell the word for a paper that shows roads and places.',
    answer: 'map', hint: 'm-a-p.' },
  { id: 'ph-g1-final-1', strand: 'phonics', grade: 1, kc: 'final-sounds', difficulty: 900,
    type: 'multiple-choice', prompt: 'What sound do you hear at the END of "cup"?',
    choices: ['/p/', '/k/', '/t/', '/m/'], answerIndex: 0 },

  // ---- Grade 2: blends, digraphs, vowel teams, magic-e ----
  { id: 'ph-g2-blend-1', strand: 'phonics', grade: 2, kc: 'blends', difficulty: 960,
    type: 'spelling', prompt: 'Spell the word for a green animal that hops and says "ribbit".',
    answer: 'frog', hint: 'It starts with the "fr" blend.' },
  { id: 'ph-g2-digraph-1', strand: 'phonics', grade: 2, kc: 'digraphs', difficulty: 980,
    type: 'multiple-choice', prompt: 'Which word has the "ch" sound?',
    choices: ['chair', 'cake', 'kite', 'sock'], answerIndex: 0 },
  { id: 'ph-g2-vowelteam-1', strand: 'phonics', grade: 2, kc: 'vowel-teams', difficulty: 1000,
    type: 'spelling', prompt: 'Spell the word for water that falls from clouds.',
    answer: 'rain', hint: 'It uses the "ai" vowel team.' },
  { id: 'ph-g2-magice-1', strand: 'phonics', grade: 2, kc: 'magic-e', difficulty: 1020,
    type: 'multiple-choice', prompt: 'Add a silent "e" to "kit". What word do you get?',
    choices: ['kite', 'kitt', 'kute', 'keet'], answerIndex: 0,
    hint: 'The "e" makes the "i" say its name.' },
  { id: 'ph-g2-vowelteam-2', strand: 'phonics', grade: 2, kc: 'vowel-teams', difficulty: 1040,
    type: 'spelling', prompt: 'Spell the tall plant with a trunk, branches, and leaves.',
    answer: 'tree', hint: 'It uses the "ee" vowel team.' },
  { id: 'ph-g2-digraph-2', strand: 'phonics', grade: 2, kc: 'digraphs', difficulty: 1060,
    type: 'multiple-choice', prompt: 'Which word has the "th" sound?',
    choices: ['thumb', 'tap', 'sun', 'fan'], answerIndex: 0 },
  { id: 'ph-g2-vowelteam-3', strand: 'phonics', grade: 2, kc: 'vowel-teams', difficulty: 1080,
    type: 'spelling', prompt: 'Spell the word for something you ride on water.',
    answer: 'boat', hint: 'It uses the "oa" vowel team.' },
  { id: 'ph-g2-blend-2', strand: 'phonics', grade: 2, kc: 'blends', difficulty: 1100,
    type: 'multiple-choice', prompt: 'Which blend do you hear at the START of "stop"?',
    choices: ['st', 'sp', 'sn', 'sl'], answerIndex: 0 },
  { id: 'ph-g2-vowelteam-4', strand: 'phonics', grade: 2, kc: 'vowel-teams', difficulty: 1120,
    type: 'spelling', prompt: 'Spell what children do at recess with games and toys.',
    answer: 'play', hint: 'It ends with the "ay" team.' },
  { id: 'ph-g2-magice-2', strand: 'phonics', grade: 2, kc: 'magic-e', difficulty: 1160,
    type: 'multiple-choice', prompt: 'Which word has a long "o" sound?',
    choices: ['rope', 'rock', 'rod', 'rob'], answerIndex: 0 },

  // ---- Grade 3: r-controlled, diphthongs, multisyllable, soft c/g ----
  { id: 'ph-g3-rcontrolled-1', strand: 'phonics', grade: 3, kc: 'r-controlled', difficulty: 1220,
    type: 'spelling', prompt: 'Spell the bright object that twinkles in the night sky.',
    answer: 'star', hint: 'It uses "ar" — s-t-a-r.' },
  { id: 'ph-g3-diphthong-1', strand: 'phonics', grade: 3, kc: 'diphthongs', difficulty: 1240,
    type: 'multiple-choice', prompt: 'Which word has the "oi" sound, like in "boy"?',
    choices: ['coin', 'cone', 'cane', 'corn'], answerIndex: 0 },
  { id: 'ph-g3-trigraph-1', strand: 'phonics', grade: 3, kc: 'igh', difficulty: 1260,
    type: 'spelling', prompt: 'Spell the time of day when it is dark and we sleep.',
    answer: 'night', hint: 'It uses "igh": n-igh-t.' },
  { id: 'ph-g3-softc-1', strand: 'phonics', grade: 3, kc: 'soft-c', difficulty: 1280,
    type: 'multiple-choice', prompt: 'In which word does "c" make the soft /s/ sound?',
    choices: ['city', 'cat', 'cup', 'cot'], answerIndex: 0 },
  { id: 'ph-g3-diphthong-2', strand: 'phonics', grade: 3, kc: 'diphthongs', difficulty: 1300,
    type: 'spelling', prompt: 'Spell the white puffy shape that floats in the sky.',
    answer: 'cloud', hint: 'It uses "ou": c-l-ou-d.' },
  { id: 'ph-g3-rcontrolled-2', strand: 'phonics', grade: 3, kc: 'r-controlled', difficulty: 1320,
    type: 'multiple-choice', prompt: 'Which word has the "or" sound, like in "corn"?',
    choices: ['thorn', 'thin', 'than', 'then'], answerIndex: 0 },
  { id: 'ph-g3-softg-1', strand: 'phonics', grade: 3, kc: 'soft-g', difficulty: 1340,
    type: 'multiple-choice', prompt: 'In which word does "g" make the soft /j/ sound?',
    choices: ['giant', 'goat', 'gum', 'gate'], answerIndex: 0 },
  { id: 'ph-g3-diphthong-3', strand: 'phonics', grade: 3, kc: 'diphthongs', difficulty: 1360,
    type: 'multiple-choice', prompt: 'Which word has the "aw" sound, like in "saw"?',
    choices: ['claw', 'clay', 'clap', 'club'], answerIndex: 0 },
  { id: 'ph-g3-vowelteam-1', strand: 'phonics', grade: 3, kc: 'vowel-teams', difficulty: 1380,
    type: 'spelling', prompt: 'Spell what you do with your teeth to food before swallowing.',
    answer: 'chew', hint: 'It uses "ew": ch-ew.' },
  { id: 'ph-g3-syllables-1', strand: 'phonics', grade: 3, kc: 'syllables', difficulty: 1420,
    type: 'multiple-choice', prompt: 'How many syllables are in the word "rabbit"?',
    choices: ['2', '1', '3', '4'], answerIndex: 0,
    hint: 'Clap it out: rab-bit.' },

  // ===================================================================
  // VOCABULARY — Vocab Vale (meaning, synonyms, antonyms, context)
  // ===================================================================
  // ---- Grade 1 ----
  { id: 'vo-g1-syn-1', strand: 'vocabulary', grade: 1, kc: 'synonyms', difficulty: 700,
    type: 'multiple-choice', prompt: 'Which word means almost the same as "big"?',
    choices: ['large', 'tiny', 'cold', 'fast'], answerIndex: 0 },
  { id: 'vo-g1-ant-1', strand: 'vocabulary', grade: 1, kc: 'antonyms', difficulty: 720,
    type: 'multiple-choice', prompt: 'Which word is the OPPOSITE of "hot"?',
    choices: ['cold', 'warm', 'big', 'wet'], answerIndex: 0 },
  { id: 'vo-g1-category-1', strand: 'vocabulary', grade: 1, kc: 'categories', difficulty: 740,
    type: 'multiple-choice', prompt: 'Which one is an ANIMAL?',
    choices: ['dog', 'chair', 'apple', 'shoe'], answerIndex: 0 },
  { id: 'vo-g1-syn-2', strand: 'vocabulary', grade: 1, kc: 'synonyms', difficulty: 760,
    type: 'multiple-choice', prompt: 'Which word means almost the same as "happy"?',
    choices: ['glad', 'sad', 'tired', 'angry'], answerIndex: 0 },
  { id: 'vo-g1-ant-2', strand: 'vocabulary', grade: 1, kc: 'antonyms', difficulty: 780,
    type: 'multiple-choice', prompt: 'Which word is the OPPOSITE of "up"?',
    choices: ['down', 'high', 'top', 'over'], answerIndex: 0 },
  { id: 'vo-g1-category-2', strand: 'vocabulary', grade: 1, kc: 'categories', difficulty: 800,
    type: 'multiple-choice', prompt: 'Which one is a COLOR?',
    choices: ['red', 'run', 'cup', 'cat'], answerIndex: 0 },
  { id: 'vo-g1-syn-3', strand: 'vocabulary', grade: 1, kc: 'synonyms', difficulty: 820,
    type: 'multiple-choice', prompt: 'Which word means almost the same as "fast"?',
    choices: ['quick', 'slow', 'long', 'soft'], answerIndex: 0 },
  { id: 'vo-g1-ant-3', strand: 'vocabulary', grade: 1, kc: 'antonyms', difficulty: 840,
    type: 'multiple-choice', prompt: 'Which word is the OPPOSITE of "day"?',
    choices: ['night', 'noon', 'sun', 'time'], answerIndex: 0 },
  { id: 'vo-g1-context-1', strand: 'vocabulary', grade: 1, kc: 'context-clues', difficulty: 860,
    type: 'multiple-choice', prompt: 'A puppy is a baby ___.',
    choices: ['dog', 'cat', 'cow', 'bird'], answerIndex: 0 },
  { id: 'vo-g1-syn-4', strand: 'vocabulary', grade: 1, kc: 'synonyms', difficulty: 900,
    type: 'multiple-choice', prompt: 'Which word means almost the same as "little"?',
    choices: ['small', 'huge', 'loud', 'warm'], answerIndex: 0 },

  // ---- Grade 2 ----
  { id: 'vo-g2-syn-1', strand: 'vocabulary', grade: 2, kc: 'synonyms', difficulty: 960,
    type: 'multiple-choice', prompt: 'Which word means almost the same as "begin"?',
    choices: ['start', 'stop', 'end', 'wait'], answerIndex: 0 },
  { id: 'vo-g2-ant-1', strand: 'vocabulary', grade: 2, kc: 'antonyms', difficulty: 980,
    type: 'multiple-choice', prompt: 'Which word is the OPPOSITE of "empty"?',
    choices: ['full', 'open', 'light', 'small'], answerIndex: 0 },
  { id: 'vo-g2-context-1', strand: 'vocabulary', grade: 2, kc: 'context-clues', difficulty: 1000,
    type: 'multiple-choice', prompt: 'The fragile glass broke the moment it fell. "Fragile" means ___.',
    choices: ['easily broken', 'very heavy', 'bright', 'sticky'], answerIndex: 0,
    hint: 'It broke right away when it fell.' },
  { id: 'vo-g2-syn-2', strand: 'vocabulary', grade: 2, kc: 'synonyms', difficulty: 1020,
    type: 'multiple-choice', prompt: 'Which word means almost the same as "shout"?',
    choices: ['yell', 'whisper', 'walk', 'sit'], answerIndex: 0 },
  { id: 'vo-g2-ant-2', strand: 'vocabulary', grade: 2, kc: 'antonyms', difficulty: 1040,
    type: 'multiple-choice', prompt: 'Which word is the OPPOSITE of "wide"?',
    choices: ['narrow', 'tall', 'round', 'long'], answerIndex: 0 },
  { id: 'vo-g2-category-1', strand: 'vocabulary', grade: 2, kc: 'categories', difficulty: 1060,
    type: 'multiple-choice', prompt: 'Which word names a FEELING?',
    choices: ['excited', 'table', 'jump', 'green'], answerIndex: 0 },
  { id: 'vo-g2-syn-3', strand: 'vocabulary', grade: 2, kc: 'synonyms', difficulty: 1080,
    type: 'multiple-choice', prompt: 'Which word means almost the same as "tired"?',
    choices: ['sleepy', 'happy', 'fast', 'hungry'], answerIndex: 0 },
  { id: 'vo-g2-context-2', strand: 'vocabulary', grade: 2, kc: 'context-clues', difficulty: 1100,
    type: 'multiple-choice', prompt: 'He was generous and shared his lunch with everyone. "Generous" means ___.',
    choices: ['giving', 'selfish', 'angry', 'quiet'], answerIndex: 0,
    hint: 'He shared with everyone.' },
  { id: 'vo-g2-ant-3', strand: 'vocabulary', grade: 2, kc: 'antonyms', difficulty: 1120,
    type: 'multiple-choice', prompt: 'Which word is the OPPOSITE of "brave"?',
    choices: ['afraid', 'strong', 'bold', 'kind'], answerIndex: 0 },
  { id: 'vo-g2-syn-4', strand: 'vocabulary', grade: 2, kc: 'synonyms', difficulty: 1160,
    type: 'multiple-choice', prompt: 'Which word means almost the same as "smart"?',
    choices: ['clever', 'silly', 'slow', 'mean'], answerIndex: 0 },

  // ---- Grade 3 ----
  { id: 'vo-g3-syn-1', strand: 'vocabulary', grade: 3, kc: 'synonyms', difficulty: 1220,
    type: 'multiple-choice', prompt: 'Which word means almost the same as "enormous"?',
    choices: ['gigantic', 'tiny', 'pretty', 'gentle'], answerIndex: 0 },
  { id: 'vo-g3-ant-1', strand: 'vocabulary', grade: 3, kc: 'antonyms', difficulty: 1240,
    type: 'multiple-choice', prompt: 'Which word is the OPPOSITE of "increase"?',
    choices: ['decrease', 'grow', 'expand', 'gather'], answerIndex: 0 },
  { id: 'vo-g3-context-1', strand: 'vocabulary', grade: 3, kc: 'context-clues', difficulty: 1260,
    type: 'multiple-choice', prompt: 'The curious student asked question after question. "Curious" means ___.',
    choices: ['eager to learn', 'bored', 'sleepy', 'unfriendly'], answerIndex: 0 },
  { id: 'vo-g3-syn-2', strand: 'vocabulary', grade: 3, kc: 'synonyms', difficulty: 1280,
    type: 'multiple-choice', prompt: 'Which word means almost the same as "furious"?',
    choices: ['angry', 'joyful', 'calm', 'curious'], answerIndex: 0 },
  { id: 'vo-g3-ant-2', strand: 'vocabulary', grade: 3, kc: 'antonyms', difficulty: 1300,
    type: 'multiple-choice', prompt: 'Which word is the OPPOSITE of "ancient"?',
    choices: ['modern', 'old', 'broken', 'huge'], answerIndex: 0 },
  { id: 'vo-g3-prefix-1', strand: 'vocabulary', grade: 3, kc: 'prefixes', difficulty: 1320,
    type: 'multiple-choice', prompt: 'The prefix "un-" in "unhappy" means ___.',
    choices: ['not', 'very', 'again', 'before'], answerIndex: 0 },
  { id: 'vo-g3-syn-3', strand: 'vocabulary', grade: 3, kc: 'synonyms', difficulty: 1340,
    type: 'multiple-choice', prompt: 'Which word means almost the same as "delicious"?',
    choices: ['tasty', 'awful', 'plain', 'spoiled'], answerIndex: 0 },
  { id: 'vo-g3-context-2', strand: 'vocabulary', grade: 3, kc: 'context-clues', difficulty: 1360,
    type: 'multiple-choice', prompt: 'The stubborn mule refused to move no matter what. "Stubborn" means ___.',
    choices: ['will not change its mind', 'very fast', 'friendly', 'tired'], answerIndex: 0 },
  { id: 'vo-g3-suffix-1', strand: 'vocabulary', grade: 3, kc: 'suffixes', difficulty: 1380,
    type: 'multiple-choice', prompt: 'The suffix "-less" in "fearless" means ___.',
    choices: ['without', 'full of', 'more', 'one who'], answerIndex: 0 },
  { id: 'vo-g3-syn-4', strand: 'vocabulary', grade: 3, kc: 'synonyms', difficulty: 1420,
    type: 'multiple-choice', prompt: 'Which word means almost the same as "rapid"?',
    choices: ['quick', 'lazy', 'heavy', 'silent'], answerIndex: 0 },

  // ===================================================================
  // SPELLING — Spellhaven (patterns, plurals, suffixes, homophones)
  // ===================================================================
  // ---- Grade 1 ----
  { id: 'sp-g1-plural-1', strand: 'spelling', grade: 1, kc: 'plurals', difficulty: 700,
    type: 'spelling', prompt: 'Spell the word for more than one cat.',
    answer: 'cats', hint: 'Add an "s" to "cat".' },
  { id: 'sp-g1-cvc-1', strand: 'spelling', grade: 1, kc: 'common-patterns', difficulty: 720,
    type: 'spelling', prompt: 'Spell the word that means to come to a halt.',
    answer: 'stop', hint: 's-t-o-p.' },
  { id: 'sp-g1-cvc-2', strand: 'spelling', grade: 1, kc: 'common-patterns', difficulty: 740,
    type: 'spelling', prompt: 'Spell what you do with your legs to leap into the air.',
    answer: 'jump', hint: 'j-u-m-p.' },
  { id: 'sp-g1-recognize-1', strand: 'spelling', grade: 1, kc: 'recognize', difficulty: 760,
    type: 'multiple-choice', prompt: 'Which one is spelled correctly?',
    choices: ['tree', 'tre', 'trea', 'treee'], answerIndex: 0 },
  { id: 'sp-g1-digraph-1', strand: 'spelling', grade: 1, kc: 'common-patterns', difficulty: 780,
    type: 'spelling', prompt: 'Spell the animal that swims and has fins and gills.',
    answer: 'fish', hint: 'It ends with "sh".' },
  { id: 'sp-g1-plural-2', strand: 'spelling', grade: 1, kc: 'plurals', difficulty: 800,
    type: 'spelling', prompt: 'Spell the word for more than one dog.',
    answer: 'dogs', hint: 'Add an "s" to "dog".' },
  { id: 'sp-g1-recognize-2', strand: 'spelling', grade: 1, kc: 'recognize', difficulty: 820,
    type: 'multiple-choice', prompt: 'Which one is spelled correctly?',
    choices: ['blue', 'bloo', 'blu', 'bleu'], answerIndex: 0 },
  { id: 'sp-g1-cvc-3', strand: 'spelling', grade: 1, kc: 'common-patterns', difficulty: 840,
    type: 'spelling', prompt: 'Spell the part of your body at the end of your arm.',
    answer: 'hand', hint: 'h-a-n-d.' },
  { id: 'sp-g1-cvc-4', strand: 'spelling', grade: 1, kc: 'common-patterns', difficulty: 860,
    type: 'spelling', prompt: 'Spell the white drink that comes from cows.',
    answer: 'milk', hint: 'm-i-l-k.' },
  { id: 'sp-g1-recognize-3', strand: 'spelling', grade: 1, kc: 'recognize', difficulty: 900,
    type: 'multiple-choice', prompt: 'Which one is spelled correctly?',
    choices: ['happy', 'hapy', 'happi', 'hapee'], answerIndex: 0 },

  // ---- Grade 2 ----
  { id: 'sp-g2-suffix-1', strand: 'spelling', grade: 2, kc: 'suffixes', difficulty: 960,
    type: 'spelling', prompt: 'Add -ing to "jump" to show it is happening now.',
    answer: 'jumping', hint: 'Just add -ing: jump + ing.' },
  { id: 'sp-g2-plural-1', strand: 'spelling', grade: 2, kc: 'plurals', difficulty: 980,
    type: 'spelling', prompt: 'Spell the word for more than one box.',
    answer: 'boxes', hint: 'Words ending in x add "-es".' },
  { id: 'sp-g2-sightword-1', strand: 'spelling', grade: 2, kc: 'sight-words', difficulty: 1000,
    type: 'spelling', prompt: 'Spell the word that answers "why": "I stayed home ___ I was sick."',
    answer: 'because', hint: 'b-e-c-a-u-s-e.' },
  { id: 'sp-g2-homophone-1', strand: 'spelling', grade: 2, kc: 'homophones', difficulty: 1020,
    type: 'multiple-choice', prompt: 'Pick the right word: "I have ___ apples in my bag."',
    choices: ['two', 'to', 'too', 'tow'], answerIndex: 0,
    hint: '"two" is the number 2.' },
  { id: 'sp-g2-suffix-2', strand: 'spelling', grade: 2, kc: 'suffixes', difficulty: 1040,
    type: 'spelling', prompt: 'Add -ed to "play" to show it already happened.',
    answer: 'played', hint: 'Just add -ed: play + ed.' },
  { id: 'sp-g2-plural-2', strand: 'spelling', grade: 2, kc: 'plurals', difficulty: 1060,
    type: 'spelling', prompt: 'Spell the word for more than one baby.',
    answer: 'babies', hint: 'Change the "y" to "ies".' },
  { id: 'sp-g2-sightword-2', strand: 'spelling', grade: 2, kc: 'sight-words', difficulty: 1080,
    type: 'spelling', prompt: 'Spell the word for a person you like to play with.',
    answer: 'friend', hint: 'There is an "i" after the "r": fr-i-end.' },
  { id: 'sp-g2-homophone-2', strand: 'spelling', grade: 2, kc: 'homophones', difficulty: 1100,
    type: 'multiple-choice', prompt: 'Pick the right word: "The dog wagged ___ tail."',
    choices: ['its', "it's", "its'", 'itts'], answerIndex: 0,
    hint: '"it\'s" is short for "it is".' },
  { id: 'sp-g2-double-1', strand: 'spelling', grade: 2, kc: 'doubling', difficulty: 1120,
    type: 'spelling', prompt: 'Add -ing to "sit" to show it is happening now.',
    answer: 'sitting', hint: 'Double the "t" before adding -ing.' },
  { id: 'sp-g2-sightword-3', strand: 'spelling', grade: 2, kc: 'sight-words', difficulty: 1160,
    type: 'spelling', prompt: 'Spell the part of the day before noon.',
    answer: 'morning', hint: 'm-o-r-n-i-n-g.' },

  // ---- Grade 3 ----
  { id: 'sp-g3-dropE-1', strand: 'spelling', grade: 3, kc: 'drop-e', difficulty: 1220,
    type: 'spelling', prompt: 'Add -ing to "make".',
    answer: 'making', hint: 'Drop the "e" before adding -ing.' },
  { id: 'sp-g3-plural-1', strand: 'spelling', grade: 3, kc: 'irregular-plurals', difficulty: 1240,
    type: 'spelling', prompt: 'Spell the word for more than one leaf.',
    answer: 'leaves', hint: 'Change "f" to "ves".' },
  { id: 'sp-g3-homophone-1', strand: 'spelling', grade: 3, kc: 'homophones', difficulty: 1260,
    type: 'multiple-choice', prompt: 'Pick the right word: "The kids rode ___ bikes to school."',
    choices: ['their', 'there', "they're", 'thare'], answerIndex: 0,
    hint: '"their" shows the bikes belong to them.' },
  { id: 'sp-g3-sightword-1', strand: 'spelling', grade: 3, kc: 'sight-words', difficulty: 1280,
    type: 'spelling', prompt: 'Spell the day that comes after today.',
    answer: 'tomorrow', hint: 'One "m", two "r"s: to-mor-row.' },
  { id: 'sp-g3-double-1', strand: 'spelling', grade: 3, kc: 'doubling', difficulty: 1300,
    type: 'spelling', prompt: 'Add -ed to "stop".',
    answer: 'stopped', hint: 'Double the "p" before adding -ed.' },
  { id: 'sp-g3-plural-2', strand: 'spelling', grade: 3, kc: 'irregular-plurals', difficulty: 1320,
    type: 'spelling', prompt: 'Spell the word for more than one child.',
    answer: 'children', hint: 'It does not just add "s".' },
  { id: 'sp-g3-homophone-2', strand: 'spelling', grade: 3, kc: 'homophones', difficulty: 1340,
    type: 'multiple-choice', prompt: 'Pick the right word: "Look — ___ playing in the park."',
    choices: ["they're", 'their', 'there', 'thier'], answerIndex: 0,
    hint: '"they\'re" is short for "they are".' },
  { id: 'sp-g3-sightword-2', strand: 'spelling', grade: 3, kc: 'sight-words', difficulty: 1360,
    type: 'spelling', prompt: 'Spell the word that describes something very pretty to look at.',
    answer: 'beautiful', hint: 'It starts "beau-": b-e-a-u-t-i-f-u-l.' },
  { id: 'sp-g3-suffix-1', strand: 'spelling', grade: 3, kc: 'suffixes', difficulty: 1380,
    type: 'spelling', prompt: 'Add -ful to "care" to mean "full of care".',
    answer: 'careful', hint: 'Just add -ful: care + ful.' },
  { id: 'sp-g3-sightword-3', strand: 'spelling', grade: 3, kc: 'sight-words', difficulty: 1420,
    type: 'spelling', prompt: 'Spell the word meaning "not the same".',
    answer: 'different', hint: 'Two "f"s and "-ent": dif-fer-ent.' },

  // ===================================================================
  // GRAMMAR — Grammar Grove (parts of speech, agreement, punctuation)
  // ===================================================================
  // ---- Grade 1 ----
  { id: 'gr-g1-noun-1', strand: 'grammar', grade: 1, kc: 'nouns', difficulty: 700,
    type: 'multiple-choice', prompt: 'Which word is a NOUN (a person, place, or thing)?',
    choices: ['ball', 'run', 'fast', 'happy'], answerIndex: 0 },
  { id: 'gr-g1-capital-1', strand: 'grammar', grade: 1, kc: 'capitalization', difficulty: 720,
    type: 'multiple-choice', prompt: 'Which word should always start with a capital letter?',
    choices: ['Sam', 'dog', 'park', 'ball'], answerIndex: 0,
    hint: 'Names of people start with a capital.' },
  { id: 'gr-g1-punct-1', strand: 'grammar', grade: 1, kc: 'punctuation', difficulty: 740,
    type: 'multiple-choice', prompt: 'Which end mark belongs after a question?',
    choices: ['?', '.', '!', ','], answerIndex: 0 },
  { id: 'gr-g1-verb-1', strand: 'grammar', grade: 1, kc: 'verbs', difficulty: 760,
    type: 'multiple-choice', prompt: 'Which word is an ACTION word (verb)?',
    choices: ['run', 'cat', 'red', 'big'], answerIndex: 0 },
  { id: 'gr-g1-agreement-1', strand: 'grammar', grade: 1, kc: 'subject-verb-agreement', difficulty: 780,
    type: 'multiple-choice', prompt: 'Choose the correct word: "I ___ a kid."',
    choices: ['am', 'is', 'are', 'be'], answerIndex: 0 },
  { id: 'gr-g1-noun-2', strand: 'grammar', grade: 1, kc: 'nouns', difficulty: 800,
    type: 'multiple-choice', prompt: 'In "The cat sat", which word is the NOUN?',
    choices: ['cat', 'the', 'sat', 'on'], answerIndex: 0 },
  { id: 'gr-g1-plural-1', strand: 'grammar', grade: 1, kc: 'plural-nouns', difficulty: 820,
    type: 'multiple-choice', prompt: 'Finish it: "One dog, two ___."',
    choices: ['dogs', 'dog', 'doges', 'dogis'], answerIndex: 0 },
  { id: 'gr-g1-capital-2', strand: 'grammar', grade: 1, kc: 'capitalization', difficulty: 840,
    type: 'multiple-choice', prompt: 'Which sentence starts correctly?',
    choices: ['The dog runs.', 'the dog runs.', 'tHe dog runs.', 'THe dog runs.'], answerIndex: 0 },
  { id: 'gr-g1-verb-2', strand: 'grammar', grade: 1, kc: 'verbs', difficulty: 860,
    type: 'multiple-choice', prompt: 'In "Dogs bark", which word is the ACTION word?',
    choices: ['bark', 'dogs', 'the', 'a'], answerIndex: 0 },
  { id: 'gr-g1-punct-2', strand: 'grammar', grade: 1, kc: 'punctuation', difficulty: 900,
    type: 'multiple-choice', prompt: 'Which end mark belongs after a telling sentence?',
    choices: ['.', '?', ',', ':'], answerIndex: 0 },

  // ---- Grade 2 ----
  { id: 'gr-g2-agreement-1', strand: 'grammar', grade: 2, kc: 'subject-verb-agreement', difficulty: 960,
    type: 'multiple-choice', prompt: 'Choose the correct word: "She ___ to school."',
    choices: ['goes', 'go', 'going', 'gone'], answerIndex: 0 },
  { id: 'gr-g2-adjective-1', strand: 'grammar', grade: 2, kc: 'adjectives', difficulty: 980,
    type: 'multiple-choice', prompt: 'Which word is an ADJECTIVE (describing word)?',
    choices: ['happy', 'jump', 'dog', 'quickly'], answerIndex: 0 },
  { id: 'gr-g2-tense-1', strand: 'grammar', grade: 2, kc: 'verb-tense', difficulty: 1000,
    type: 'multiple-choice', prompt: 'What is the PAST tense of "walk"?',
    choices: ['walked', 'walks', 'walking', 'walk'], answerIndex: 0 },
  { id: 'gr-g2-pronoun-1', strand: 'grammar', grade: 2, kc: 'pronouns', difficulty: 1020,
    type: 'multiple-choice', prompt: 'Choose the right word: "Sam is tall. ___ plays ball."',
    choices: ['He', 'She', 'It', 'They'], answerIndex: 0 },
  { id: 'gr-g2-verb-1', strand: 'grammar', grade: 2, kc: 'verbs', difficulty: 1040,
    type: 'multiple-choice', prompt: 'Which word is a VERB?',
    choices: ['sing', 'song', 'loud', 'music'], answerIndex: 0 },
  { id: 'gr-g2-agreement-2', strand: 'grammar', grade: 2, kc: 'subject-verb-agreement', difficulty: 1060,
    type: 'multiple-choice', prompt: 'Choose the correct word: "The cats ___ sleeping."',
    choices: ['are', 'is', 'am', 'be'], answerIndex: 0 },
  { id: 'gr-g2-adjective-2', strand: 'grammar', grade: 2, kc: 'adjectives', difficulty: 1080,
    type: 'multiple-choice', prompt: 'Pick the describing word: "a ___ dog ran by."',
    choices: ['big', 'ran', 'dog', 'by'], answerIndex: 0 },
  { id: 'gr-g2-tense-2', strand: 'grammar', grade: 2, kc: 'verb-tense', difficulty: 1100,
    type: 'multiple-choice', prompt: 'What is the PAST tense of "run"?',
    choices: ['ran', 'runned', 'running', 'runs'], answerIndex: 0 },
  { id: 'gr-g2-punct-1', strand: 'grammar', grade: 2, kc: 'commas', difficulty: 1120,
    type: 'multiple-choice', prompt: 'Where does a comma go? "I bought apples___ pears, and figs."',
    choices: ['a comma after apples', 'no comma', 'a period', 'a question mark'], answerIndex: 0,
    hint: 'Lists use commas between items.' },
  { id: 'gr-g2-pronoun-2', strand: 'grammar', grade: 2, kc: 'pronouns', difficulty: 1160,
    type: 'multiple-choice', prompt: 'Which pronoun replaces "Mia and Ana"?',
    choices: ['they', 'he', 'she', 'it'], answerIndex: 0 },

  // ---- Grade 3 ----
  { id: 'gr-g3-agreement-1', strand: 'grammar', grade: 3, kc: 'subject-verb-agreement', difficulty: 1220,
    type: 'multiple-choice', prompt: 'Choose the correct word: "Each of the boys ___ a bike."',
    choices: ['has', 'have', 'having', 'haves'], answerIndex: 0,
    hint: '"Each" is treated as one.' },
  { id: 'gr-g3-adverb-1', strand: 'grammar', grade: 3, kc: 'adverbs', difficulty: 1240,
    type: 'multiple-choice', prompt: 'Which word is the ADVERB in "She ran quickly"?',
    choices: ['quickly', 'she', 'ran', 'the'], answerIndex: 0 },
  { id: 'gr-g3-tense-1', strand: 'grammar', grade: 3, kc: 'irregular-verbs', difficulty: 1260,
    type: 'multiple-choice', prompt: 'What is the PAST tense of "bring"?',
    choices: ['brought', 'bringed', 'brang', 'brings'], answerIndex: 0 },
  { id: 'gr-g3-conjunction-1', strand: 'grammar', grade: 3, kc: 'conjunctions', difficulty: 1280,
    type: 'multiple-choice', prompt: 'Which word is a conjunction that joins two ideas?',
    choices: ['but', 'dog', 'happy', 'slowly'], answerIndex: 0 },
  { id: 'gr-g3-possessive-1', strand: 'grammar', grade: 3, kc: 'possessives', difficulty: 1300,
    type: 'multiple-choice', prompt: 'In "the dog\'s bone", what does the apostrophe show?',
    choices: ['the bone belongs to the dog', 'more than one dog', 'an action', 'a question'], answerIndex: 0 },
  { id: 'gr-g3-agreement-2', strand: 'grammar', grade: 3, kc: 'subject-verb-agreement', difficulty: 1320,
    type: 'multiple-choice', prompt: 'Choose the correct word: "Neither answer ___ right."',
    choices: ['is', 'are', 'were', 'be'], answerIndex: 0 },
  { id: 'gr-g3-comparative-1', strand: 'grammar', grade: 3, kc: 'comparatives', difficulty: 1340,
    type: 'multiple-choice', prompt: 'Finish the pattern: "big, bigger, ___."',
    choices: ['biggest', 'most big', 'bigger', 'biggor'], answerIndex: 0 },
  { id: 'gr-g3-preposition-1', strand: 'grammar', grade: 3, kc: 'prepositions', difficulty: 1360,
    type: 'multiple-choice', prompt: 'Which word is a preposition (shows position)?',
    choices: ['under', 'jump', 'happy', 'dog'], answerIndex: 0 },
  { id: 'gr-g3-punct-1', strand: 'grammar', grade: 3, kc: 'quotation-marks', difficulty: 1380,
    type: 'multiple-choice', prompt: 'Quotation marks ("  ") are placed around ___.',
    choices: ['the exact words someone says', 'a list', 'a date', 'a question only'], answerIndex: 0 },
  { id: 'gr-g3-tense-2', strand: 'grammar', grade: 3, kc: 'verb-tense', difficulty: 1420,
    type: 'multiple-choice', prompt: 'Choose the FUTURE tense: "I ___ visit Grandma tomorrow."',
    choices: ['will', 'did', 'was', 'am'], answerIndex: 0 },

  // ===================================================================
  // COMPREHENSION — Story Sea (literal recall, inference, main idea)
  // ===================================================================
  // ---- Grade 1 ----
  { id: 'co-g1-literal-1', strand: 'comprehension', grade: 1, kc: 'literal-recall', difficulty: 700,
    type: 'multiple-choice', prompt: 'Read: "Tom has a red hat." What color is Tom\'s hat?',
    choices: ['red', 'blue', 'green', 'black'], answerIndex: 0 },
  { id: 'co-g1-literal-2', strand: 'comprehension', grade: 1, kc: 'literal-recall', difficulty: 720,
    type: 'multiple-choice', prompt: 'Read: "The dog ran to the park." Where did the dog run?',
    choices: ['the park', 'the store', 'the pool', 'the zoo'], answerIndex: 0 },
  { id: 'co-g1-literal-3', strand: 'comprehension', grade: 1, kc: 'literal-recall', difficulty: 740,
    type: 'multiple-choice', prompt: 'Read: "Mia ate a big apple." What did Mia eat?',
    choices: ['an apple', 'a banana', 'a pear', 'a plum'], answerIndex: 0 },
  { id: 'co-g1-inference-1', strand: 'comprehension', grade: 1, kc: 'inference', difficulty: 760,
    type: 'multiple-choice', prompt: 'Read: "It was raining, so Ben took his umbrella." Why did Ben take it?',
    choices: ['it was raining', 'it was sunny', 'it was night', 'he was hungry'], answerIndex: 0,
    hint: 'What was the weather like?' },
  { id: 'co-g1-literal-4', strand: 'comprehension', grade: 1, kc: 'literal-recall', difficulty: 780,
    type: 'multiple-choice', prompt: 'Read: "The cat is on the mat." Where is the cat?',
    choices: ['on the mat', 'in the box', 'under the bed', 'on the roof'], answerIndex: 0 },
  { id: 'co-g1-literal-5', strand: 'comprehension', grade: 1, kc: 'literal-recall', difficulty: 800,
    type: 'multiple-choice', prompt: 'Read: "Sara has three pens." How many pens does Sara have?',
    choices: ['three', 'two', 'four', 'one'], answerIndex: 0 },
  { id: 'co-g1-inference-2', strand: 'comprehension', grade: 1, kc: 'inference', difficulty: 820,
    type: 'multiple-choice', prompt: 'Read: "Max smiled because he won the race." How did Max feel?',
    choices: ['happy', 'sad', 'angry', 'scared'], answerIndex: 0 },
  { id: 'co-g1-literal-6', strand: 'comprehension', grade: 1, kc: 'literal-recall', difficulty: 840,
    type: 'multiple-choice', prompt: 'Read: "Pat fed the fish in the morning." Who did Pat feed?',
    choices: ['the fish', 'the dog', 'the bird', 'the cat'], answerIndex: 0 },
  { id: 'co-g1-inference-3', strand: 'comprehension', grade: 1, kc: 'inference', difficulty: 860,
    type: 'multiple-choice', prompt: 'Read: "Ana put on a coat, hat, and gloves." The weather was probably ___.',
    choices: ['cold', 'hot', 'rainy', 'windy'], answerIndex: 0,
    hint: 'What do you wear when it is cold?' },
  { id: 'co-g1-literal-7', strand: 'comprehension', grade: 1, kc: 'literal-recall', difficulty: 900,
    type: 'multiple-choice', prompt: 'Read: "The bird flew up high into the sky." Which way did the bird fly?',
    choices: ['up', 'down', 'left', 'back'], answerIndex: 0 },

  // ---- Grade 2 ----
  { id: 'co-g2-mainidea-1', strand: 'comprehension', grade: 2, kc: 'main-idea', difficulty: 960,
    type: 'multiple-choice', prompt: 'Read: "Bees live in hives. They make honey. They help flowers grow." What is this mostly about?',
    choices: ['bees', 'flowers', 'rain', 'trees'], answerIndex: 0 },
  { id: 'co-g2-inference-1', strand: 'comprehension', grade: 2, kc: 'inference', difficulty: 980,
    type: 'multiple-choice', prompt: 'Read: "Lily yawned and rubbed her eyes." Lily was probably ___.',
    choices: ['sleepy', 'hungry', 'angry', 'cold'], answerIndex: 0 },
  { id: 'co-g2-sequence-1', strand: 'comprehension', grade: 2, kc: 'sequence', difficulty: 1000,
    type: 'multiple-choice', prompt: 'Read: "First Jo woke up. Then she ate. Last she went to school." What did Jo do FIRST?',
    choices: ['woke up', 'ate', 'went to school', 'played'], answerIndex: 0 },
  { id: 'co-g2-literal-1', strand: 'comprehension', grade: 2, kc: 'literal-recall', difficulty: 1020,
    type: 'multiple-choice', prompt: 'Read: "The team won the game by two points on Friday." When did they win?',
    choices: ['Friday', 'Monday', 'Sunday', 'Tuesday'], answerIndex: 0 },
  { id: 'co-g2-inference-2', strand: 'comprehension', grade: 2, kc: 'inference', difficulty: 1040,
    type: 'multiple-choice', prompt: 'Read: "Ben\'s tummy growled and he eyed the snacks." Ben was probably ___.',
    choices: ['hungry', 'tired', 'bored', 'sick'], answerIndex: 0 },
  { id: 'co-g2-cause-1', strand: 'comprehension', grade: 2, kc: 'cause-effect', difficulty: 1060,
    type: 'multiple-choice', prompt: 'Read: "The plant drooped because no one watered it." Why did the plant droop?',
    choices: ['no one watered it', 'too much sun', 'it was cut', 'a bug ate it'], answerIndex: 0 },
  { id: 'co-g2-mainidea-2', strand: 'comprehension', grade: 2, kc: 'main-idea', difficulty: 1080,
    type: 'multiple-choice', prompt: 'Read: "Brushing keeps teeth clean. It stops cavities. It makes a bright smile." This is mostly about ___.',
    choices: ['brushing teeth', 'eating candy', 'going to bed', 'playing games'], answerIndex: 0 },
  { id: 'co-g2-predict-1', strand: 'comprehension', grade: 2, kc: 'prediction', difficulty: 1100,
    type: 'multiple-choice', prompt: 'Read: "Dark clouds rolled in and thunder boomed." What will probably happen next?',
    choices: ['it will rain', 'the sun comes out', 'it will snow', 'a rainbow forms'], answerIndex: 0 },
  { id: 'co-g2-literal-2', strand: 'comprehension', grade: 2, kc: 'literal-recall', difficulty: 1120,
    type: 'multiple-choice', prompt: 'Read: "Grandpa gave Nina a blue bike for her birthday." What color was the bike?',
    choices: ['blue', 'red', 'green', 'pink'], answerIndex: 0 },
  { id: 'co-g2-inference-3', strand: 'comprehension', grade: 2, kc: 'inference', difficulty: 1160,
    type: 'multiple-choice', prompt: 'Read: "Sand was everywhere, waves crashed, and gulls cried." Where is this story set?',
    choices: ['the beach', 'a forest', 'a city', 'a farm'], answerIndex: 0 },

  // ---- Grade 3 ----
  { id: 'co-g3-mainidea-1', strand: 'comprehension', grade: 3, kc: 'main-idea', difficulty: 1220,
    type: 'multiple-choice', prompt: 'Read: "Sea turtles travel far to lay eggs. They swim for miles. Then they return to the sea." The main idea is that sea turtles ___.',
    choices: ['travel to lay their eggs', 'are very small', 'eat only fish', 'live on land'], answerIndex: 0 },
  { id: 'co-g3-trait-1', strand: 'comprehension', grade: 3, kc: 'character-traits', difficulty: 1240,
    type: 'multiple-choice', prompt: 'Read: "Even when the others quit, Sam kept trying until he finished." Sam is ___.',
    choices: ['determined', 'lazy', 'shy', 'rude'], answerIndex: 0 },
  { id: 'co-g3-cause-1', strand: 'comprehension', grade: 3, kc: 'cause-effect', difficulty: 1260,
    type: 'multiple-choice', prompt: 'Read: "Because the river flooded, the town closed the bridge." What was the EFFECT of the flood?',
    choices: ['the bridge was closed', 'the river dried up', 'school started', 'it snowed'], answerIndex: 0 },
  { id: 'co-g3-purpose-1', strand: 'comprehension', grade: 3, kc: 'authors-purpose', difficulty: 1280,
    type: 'multiple-choice', prompt: 'A text titled "How to Plant a Seed" with numbered steps is written mainly to ___.',
    choices: ['teach how to do something', 'tell a funny story', 'sell a toy', 'share a poem'], answerIndex: 0 },
  { id: 'co-g3-sequence-1', strand: 'comprehension', grade: 3, kc: 'sequence', difficulty: 1300,
    type: 'multiple-choice', prompt: 'Read: "After mixing the batter, Lia poured it in the pan. Finally she baked the cake." What did Lia do LAST?',
    choices: ['baked the cake', 'mixed the batter', 'poured the batter', 'bought eggs'], answerIndex: 0 },
  { id: 'co-g3-inference-1', strand: 'comprehension', grade: 3, kc: 'inference', difficulty: 1320,
    type: 'multiple-choice', prompt: 'Read: "Mr. Diaz checked the empty seats and sighed before starting the show." Mr. Diaz probably felt ___.',
    choices: ['disappointed', 'thrilled', 'sleepy', 'hungry'], answerIndex: 0 },
  { id: 'co-g3-vocab-1', strand: 'comprehension', grade: 3, kc: 'vocab-in-context', difficulty: 1340,
    type: 'multiple-choice', prompt: 'Read: "The path was so narrow that only one person could pass." In this story, "narrow" means ___.',
    choices: ['not wide', 'very long', 'muddy', 'steep'], answerIndex: 0 },
  { id: 'co-g3-compare-1', strand: 'comprehension', grade: 3, kc: 'compare-contrast', difficulty: 1360,
    type: 'multiple-choice', prompt: 'Read: "Frogs live in water and on land, but toads stay mostly on land." How are frogs and toads DIFFERENT?',
    choices: ['where they live', 'both are reptiles', 'both can fly', 'their color only'], answerIndex: 0 },
  { id: 'co-g3-conclusion-1', strand: 'comprehension', grade: 3, kc: 'drawing-conclusions', difficulty: 1380,
    type: 'multiple-choice', prompt: 'Read: "Mud tracks led to the door, and the dog\'s paws were wet." You can conclude that the dog ___.',
    choices: ['walked through mud', 'was sleeping', 'ate dinner', 'was at the vet'], answerIndex: 0 },
  { id: 'co-g3-detail-1', strand: 'comprehension', grade: 3, kc: 'key-details', difficulty: 1420,
    type: 'multiple-choice', prompt: 'Read: "The hikers reached the summit at noon after climbing for three hours." How long did they climb?',
    choices: ['three hours', 'one hour', 'all day', 'three days'], answerIndex: 0 },

  // ===================================================================
  // WRITING — Quill Keep (sentence building, capitalization, punctuation)
  // ===================================================================
  // ---- Grade 1 ----
  { id: 'wr-g1-order-1', strand: 'writing', grade: 1, kc: 'word-order', difficulty: 700,
    type: 'word-order', prompt: 'Put the words in order to make a sentence.',
    answer: ['I', 'see', 'a', 'cat'] },
  { id: 'wr-g1-order-2', strand: 'writing', grade: 1, kc: 'word-order', difficulty: 720,
    type: 'word-order', prompt: 'Put the words in order to make a sentence.',
    answer: ['The', 'dog', 'is', 'big'] },
  { id: 'wr-g1-order-3', strand: 'writing', grade: 1, kc: 'word-order', difficulty: 740,
    type: 'word-order', prompt: 'Put the words in order to make a sentence.',
    answer: ['We', 'like', 'to', 'play'] },
  { id: 'wr-g1-punct-1', strand: 'writing', grade: 1, kc: 'sentence-mechanics', difficulty: 760,
    type: 'multiple-choice', prompt: 'Which one is written correctly?',
    choices: ['The cat is fun.', 'the cat is fun', 'The cat is fun', 'the cat is fun.'], answerIndex: 0,
    hint: 'Start with a capital and end with a period.' },
  { id: 'wr-g1-order-4', strand: 'writing', grade: 1, kc: 'word-order', difficulty: 780,
    type: 'word-order', prompt: 'Put the words in order to make a sentence.',
    answer: ['She', 'has', 'a', 'hat'] },
  { id: 'wr-g1-order-5', strand: 'writing', grade: 1, kc: 'word-order', difficulty: 800,
    type: 'word-order', prompt: 'Put the words in order to make a sentence.',
    answer: ['Cats', 'can', 'run', 'fast'] },
  { id: 'wr-g1-capital-1', strand: 'writing', grade: 1, kc: 'capitalization', difficulty: 820,
    type: 'multiple-choice', prompt: 'Which sentence has the right capital letter?',
    choices: ['My name is Pat.', 'my name is pat.', 'my name is Pat.', 'My name is pat.'], answerIndex: 0 },
  { id: 'wr-g1-order-6', strand: 'writing', grade: 1, kc: 'word-order', difficulty: 840,
    type: 'word-order', prompt: 'Put the words in order to make a sentence.',
    answer: ['I', 'am', 'very', 'happy'] },
  { id: 'wr-g1-order-7', strand: 'writing', grade: 1, kc: 'word-order', difficulty: 860,
    type: 'word-order', prompt: 'Put the words in order to make a sentence.',
    answer: ['The', 'sun', 'is', 'hot'] },
  { id: 'wr-g1-punct-2', strand: 'writing', grade: 1, kc: 'sentence-mechanics', difficulty: 900,
    type: 'multiple-choice', prompt: 'Which end mark best finishes: "Are you ready___"',
    choices: ['?', '.', ',', '!'], answerIndex: 0 },

  // ---- Grade 2 ----
  { id: 'wr-g2-order-1', strand: 'writing', grade: 2, kc: 'sentence-building', difficulty: 960,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['We', 'went', 'to', 'the', 'park'] },
  { id: 'wr-g2-order-2', strand: 'writing', grade: 2, kc: 'sentence-building', difficulty: 980,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['My', 'friend', 'has', 'a', 'dog'] },
  { id: 'wr-g2-punct-1', strand: 'writing', grade: 2, kc: 'punctuation', difficulty: 1000,
    type: 'multiple-choice', prompt: 'Which sentence is punctuated correctly?',
    choices: ['Where is my book?', 'Where is my book.', 'where is my book?', 'Where is my book'], answerIndex: 0 },
  { id: 'wr-g2-order-3', strand: 'writing', grade: 2, kc: 'sentence-building', difficulty: 1020,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['The', 'bird', 'can', 'fly', 'high'] },
  { id: 'wr-g2-order-4', strand: 'writing', grade: 2, kc: 'sentence-building', difficulty: 1040,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['I', 'like', 'to', 'read', 'books'] },
  { id: 'wr-g2-complete-1', strand: 'writing', grade: 2, kc: 'complete-sentences', difficulty: 1060,
    type: 'multiple-choice', prompt: 'Which one is a COMPLETE sentence?',
    choices: ['The dog barked loudly.', 'The big brown dog.', 'Ran very fast.', 'Under the table.'], answerIndex: 0,
    hint: 'A complete sentence has a naming part and an action part.' },
  { id: 'wr-g2-order-5', strand: 'writing', grade: 2, kc: 'sentence-building', difficulty: 1080,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['She', 'ran', 'very', 'fast', 'today'] },
  { id: 'wr-g2-order-6', strand: 'writing', grade: 2, kc: 'sentence-building', difficulty: 1100,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['They', 'play', 'in', 'the', 'yard'] },
  { id: 'wr-g2-capital-1', strand: 'writing', grade: 2, kc: 'capitalization', difficulty: 1120,
    type: 'multiple-choice', prompt: 'Which word in "we visited paris" needs a capital letter?',
    choices: ['paris', 'we', 'visited', 'none'], answerIndex: 0,
    hint: 'Names of places are capitalized.' },
  { id: 'wr-g2-order-7', strand: 'writing', grade: 2, kc: 'sentence-building', difficulty: 1160,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['We', 'eat', 'lunch', 'at', 'noon'] },

  // ---- Grade 3 ----
  { id: 'wr-g3-order-1', strand: 'writing', grade: 3, kc: 'sentence-building', difficulty: 1220,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['The', 'brave', 'knight', 'saved', 'the', 'town'] },
  { id: 'wr-g3-order-2', strand: 'writing', grade: 3, kc: 'sentence-building', difficulty: 1240,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['After', 'school', 'we', 'walked', 'home'] },
  { id: 'wr-g3-combine-1', strand: 'writing', grade: 3, kc: 'compound-sentences', difficulty: 1260,
    type: 'multiple-choice', prompt: 'Which word best joins these into one sentence? "I wanted to play ___ it was raining."',
    choices: ['but', 'so', 'or', 'because'], answerIndex: 0,
    hint: 'The two parts show a contrast.' },
  { id: 'wr-g3-order-3', strand: 'writing', grade: 3, kc: 'sentence-building', difficulty: 1280,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['My', 'sister', 'and', 'I', 'baked', 'cookies'] },
  { id: 'wr-g3-order-4', strand: 'writing', grade: 3, kc: 'sentence-building', difficulty: 1300,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['The', 'rain', 'fell', 'all', 'night', 'long'] },
  { id: 'wr-g3-comma-1', strand: 'writing', grade: 3, kc: 'commas', difficulty: 1320,
    type: 'multiple-choice', prompt: 'Which sentence uses commas correctly in a list?',
    choices: ['I packed socks, shoes, and a hat.', 'I packed socks shoes and a hat.', 'I packed, socks shoes and a hat.', 'I packed socks, shoes and, a hat.'], answerIndex: 0 },
  { id: 'wr-g3-order-5', strand: 'writing', grade: 3, kc: 'sentence-building', difficulty: 1340,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['Slowly', 'the', 'turtle', 'crossed', 'the', 'road'] },
  { id: 'wr-g3-order-6', strand: 'writing', grade: 3, kc: 'sentence-building', difficulty: 1360,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['We', 'will', 'visit', 'the', 'zoo', 'tomorrow'] },
  { id: 'wr-g3-quote-1', strand: 'writing', grade: 3, kc: 'quotation-marks', difficulty: 1380,
    type: 'multiple-choice', prompt: 'Which sentence puts the quotation marks correctly?',
    choices: ['Mom said, "Time for bed."', 'Mom said, Time for bed.', 'Mom said "Time for bed.', 'Mom said, Time for "bed."'], answerIndex: 0 },
  { id: 'wr-g3-order-7', strand: 'writing', grade: 3, kc: 'sentence-building', difficulty: 1420,
    type: 'word-order', prompt: 'Arrange the words into a correct sentence.',
    answer: ['The', 'curious', 'cat', 'climbed', 'the', 'tall', 'tree'] },
];
